# Generated by Django 5.2.7 on 2025-10-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africantouragency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
